name: flutterdemo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.13.4

  english_words: ^4.0.0
  provider: ^6.0.0
  dio: ^5.2.1+1
  json_annotation: ^4.8.1
  cloud_firestore_odm: ^1.0.0-dev.61
  multi_select_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - certificates/localhost.crt